# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dd5913a05efe1b782ca3d0229866439389030e4466b72e4374200f4368c9bc842002ee9afcdf3cd88ea2cf25d7a41911a46dc6cdafc2be6863627849ca9a0d8

test:
  secret_key_base: dbb996ff6ca8dc1d53e5409ec78adcc1cb4873c4329f8f1fb2b550b2a611b21e32ec6a5e032dca9f957f7aa1e1434b6b8c25a177ad7a690a40dd1225a41fa071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
